### ISSUE TITLE
Update Podcast Feed to set is_comment_feed to FALSE

### ISSUE THREAD

**Issue by tannerm** [Church-Plugins/cp-library#78]
The [Disable Comments](https://plugins.trac.wordpress.org/browser/disable-comments/) plugin runs a filter on `template_redirect` (priority level 9) and if `is_comment_feed()` returns true, it kills the request. We need to update the query before this point to set `is_comment_feed = false` if we are in a `podcast` feed.

**Comment by jjroley** [comment]
@tannerm made a PR for this #81

**Comment by jjroley** [comment]
Addressed in #81
